### ISSUE TITLE
Working with Rest notes

### ISSUE THREAD

**Issue by skosgi242** [YatingMusic/miditoolkit#13]
Hi, Is there any way to write rests to Midi? How is the parser handling with rests when reading from Midi?

**Comment by wayne391** [comment]
Hi, there is no "rest" event in Midi. Rests are only in scores.

https://stackoverflow.com/questions/56102938/unable-to-write-rest-objects-in-midi-file

> Rests are only there to show a player where to not play notes in a bar. But MIDI doesn't know anything about bars (if you see bars in a MIDI file they are essentially comments) and so it doesn't need rests either.
