### ISSUE TITLE
sklearn package as a dependency is missing while installed via pip

### ISSUE THREAD

**Issue by salu133445** [YatingMusic/miditoolkit#2]
Hi,

Thanks for the great package. It seems that the _sklearn_ package as a dependency is missing during the installation. I installed the package via `pip install miditoolkit`. While importing the pianoroll submodule, I encountered the error `ModuleNotFoundError: No module named 'sklearn'`. I believe the sklearn package should be listed as a required dependency. Again, thanks for the great work.

**Comment by salu133445** [comment]
Oops...I just realized that the version of this package on PYPI is somehow outdated. Anyway, hope you can update it to the current version soon. Thanks!

**Comment by wayne391** [comment]
Hi, I've updated the package (0.1.8) and also deleted all redundant packages. 
It should work now :).

BTW, codes for piano-roll visualization are not well-organized. I am working on it.
