### ISSUE TITLE
from midi2dict import midi_to_lyrics

### ISSUE THREAD

**Issue by HuntZhaozq** [YatingMusic/miditoolkit#47]
Hello, I have a question. I am studying the muzic project. This project use miditoolkit. And in its code, also use `from midi2dict import midi_to_lyrics`. I wonder if this `midi2dict` is a part of `miditoolkit`. Or where this `midi2dict` from ?

**Comment by Natooz** [comment]
Hi,
I think `midi2dict` refers to a file within the muzic project, as it is not part of miditoolkit, and does not exist on pypi.
