### ISSUE TITLE
Bring back `mido` key name matching during MIDI `dump`?

### ISSUE THREAD

**Issue by gudgud96** [YatingMusic/miditoolkit#54]
Hi @Natooz,

I find that in the latest version of `miditoolkit`, the mido key name matching step is being removed, as per this PR:

https://github.com/YatingMusic/miditoolkit/pull/30/files#diff-7df500cafd3a75780266fa6f1900809ac78174fe5b3c94362cadc8ccdff905e8L492

May I ask why this part is being removed? As making sure the key signature name to be compatible with `mido` might be useful for saving MIDI, when key signature is manually inserted.

**Comment by Natooz** [comment]
Hi,

I think this has been removed as the `KeySignature` objects should hold the same names as those in Mido.
How exactly are you manually adding them?

**Comment by gudgud96** [comment]
I see! In the case which I use an external key detector based on the MIDI notes, and construct `KeySignature` object myself with `key_name` provided, `key_name` is not enforced to be `mido`-compatible.

This used to be handled during `dump` with the `mido` key name mapping.

**Comment by Natooz** [comment]
Ok so I assume you are using key numbers instead?

**Comment by gudgud96** [comment]
No, I am not using key numbers, I am creating KeySignature using a key name.

A minimal reproducible example:
```
import miditoolkit

mid = miditoolkit.MidiFile("some_mid.mid")
mid.key_signature_changes = [miditoolkit.midi.containers.KeySignature("D#", 0)]
mid.dump("new_mid.mid")
```

In the previous versions this code runs without issues, because:
(i) when `KeySignature` is created, `_key_name_to_key_number` is called and `self.key_number` is set;
(ii) during `dump`, `key_number_to_mido_key_name` is called to get a `mido`-compatible name before writing into `mido` streams.

When the mapping is removed in the new version, the above code throws an error.

**Comment by Natooz** [comment]
Thank you for the example! Indeed the key names didn't match. I put back `key_number_to_mido_key_name` as it's the easiest fix.

There is one test case not passing, unfortunately I don't have the time to handle this right now.

And btw, ou might be interested in [symusic](https://github.com/Yikai-Liao/symusic)

**Comment by gudgud96** [comment]
Thank you for your very prompt response. This should fix the issue.

For your failed test case I believe it's because Python 3.8 does not support `zip(strict=False)`. Maybe `strict=False` is not needed (I think the linter adds it)? Or omitting 3.8 from running tests might also be a solution.

Thanks for mentioning symusic! Yes I am aware of it.
